### Create a demo user
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "Gang",
  "email": "gang.wen@gmail.com",
  "password": "password"
}

### Acquire JWT token
### OAUTH2_TOKEN=$(http --body POST :8080/token --auth Gang:password)
POST http://localhost:8080/api/auth/token
Accept: application/json
Authorization: Basic Gang password

> {% client.global.set("auth_token", response.body); %}

### Access secure endpoints
GET http://localhost:8080/api/me
Authorization: Bearer {{auth_token}}

### Google login
POST http://localhost:8080/api/auth/social
Content-Type: application/json

{
  "provider": "google",
  "authorizationCode": "gang.wen@gmail.com"
}


### Get JWT Token
GET http://localhost:8080/api/auth/signup
Accept: application/json
Authorization: Basic Gang password

### Invalid oauth2token request
POST http://localhost:8080/api/auth/oauth2token
Content-Type: application/json
Accept: application/json

{
   "provider": "google"
}

### Use Token to get messages
### http :8080/api/auth/signup "Authorization: Bearer $OAUTH2_TOKEN"
GET http://localhost:8080/api/auth/signup
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJHYW5nIiwic3ViIjoiR2FuZyIsImV4cCI6MTY4NTI1MTc0NywiaWF0IjoxNjg1MjE1NzQ3LCJzY29wZSI6IlVTRVIifQ.bbVAtujQVhwV2oaKIltBg8pT92J04aljw6zF3pLwgk6ZZYfgSuUNHOzSZoR6fd5jjd4v_pB-kezqM9NQsiLd_2TaJkVFgjGh7sjQJg3BWTYIaoqJl25dw0_5MnNJTx3tZmQRT2dWh0R9PlTarC7H9XDksGFsuT71FQU05TUic_sc59Hw9UIMjvMLDmUQavVtgYQILxd_LQ7Z-yqLc7jNcLUST2lNZ0I7H0mPovHz1XCooWxBQSBI_r-jYizFf7_vm3_TLDngb9issRCuIbqGP-arlbBk8ZIh9zEYAdN3qYowHJiG9flYvEC1RKFY1OwqyVABdNeynnIlqL0wSSRT5Q

### Create another demo user without full fields
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "Tan",
  "email": "tan.wen@gmail.com"
}

### Get access token from oauth2 server
### OAUTH2_TOKEN=$(http -auth spring:secret -f POST :9090/oauth2/token grant_trype=client_credientials | jq -r '.acces_token')