spring:
  application:
    name: airbnb-clone-server

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
    always-use-message-format: true


logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

app:
  auth:
    jwt:
      iss: https://www.guludoc.com
      private-key: classpath:app.key
      public-key: classpath:app.pub
      access-token-expiry-in-seconds: 60
      refresh-token-expiry-in-hours: 3600

    providers:
      google:
        client-id: ${GOOGLE_OAUTH_CLIENT_ID}
        client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
        redirect-url: http://localhost:3000
      github:
        client-id: ${OAUTH2_GITHUB_CLIENT_ID}
        client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
        redirect-url: http://localhost:8080/api/auth/callback/github
